version: "3"

services:
  jasmin_sms_redis:
    image: redis:alpine
    restart: unless-stopped

  jasmin_sms_amq:
    image: rabbitmq:alpine
    restart: unless-stopped

  jasmin_sms_jasmin:
    image: jookies/jasmin:latest
    restart: unless-stopped
    volumes:
      # - ./gluon/opt:/opt
      - ./gluon/store:/etc/jasmin/store
      # - ./gluon/log:/var/log/jasmin
    ports:
      - 5634:2775
      - 7687:8990
    depends_on:
      - jasmin_sms_redis
      - jasmin_sms_amq
    environment:
      REDIS_CLIENT_HOST: jasmin_sms_redis
      AMQP_BROKER_HOST: jasmin_sms_amq