version: "3"

services:
  jasmin_sms_configurer:
    image: gluontech/jasmin_sms_configurer
    restart: unless-stopped
    environment:
      - AMPQ_HOST=${AMPQ_HOST}
      - AMPQ_VHOST=${AMPQ_VHOST}
      - AMPQ_PORT=${AMPQ_PORT}
      - AMPQ_USERNAME=${AMPQ_USERNAME}
      - AMPQ_PASSWORD=${AMPQ_PASSWORD}
      - AMPQ_QUEUE_NAME=${AMPQ_QUEUE_NAME}
      - AMPQ_EXCHANGE_NAME=${AMPQ_EXCHANGE_NAME}
      - JASMIN_SMS_SYNC_API_HOST=${JASMIN_SMS_SYNC_API_HOST}
      - JASMIN_SMS_SYNC_API_PORT=${JASMIN_SMS_SYNC_API_PORT}

  jasmin_sms_redis:
    image: redis:alpine
    restart: unless-stopped

  jasmin_sms_amq:
    image: rabbitmq:alpine
    restart: unless-stopped

  jasmin_sms_jasmin:
    image: jookies/jasmin:latest
    restart: unless-stopped
    container_name: jasmin
    volumes:
      - ./gluon/store:/etc/jasmin/store
      - ./gluon/log:/var/log/jasmin
    ports:
      - 2775:2775
      - 8990:8990
      - 1401:1401
    depends_on:
      - jasmin_sms_redis
      - jasmin_sms_amq
    environment:
      REDIS_CLIENT_HOST: jasmin_sms_redis
      AMQP_BROKER_HOST: jasmin_sms_amq

  jasmin_sms_server_ampq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - 15672:15672
      - 5672:5672
  
  jasmin_sms_sync_api:
    image: gluontech/jasmin_sms_sync_api
    restart: unless-stopped
    ports:
      - 3001:5000
    environment:
      - AMPQ_HOST=${AMPQ_HOST}
      - AMPQ_VHOST=${AMPQ_VHOST}
      - AMPQ_PORT=${AMPQ_PORT}
      - AMPQ_USERNAME=${AMPQ_USERNAME}
      - AMPQ_PASSWORD=${AMPQ_PASSWORD}
      - AMPQ_QUEUE_NAME=${AMPQ_QUEUE_NAME}
      - AMPQ_EXCHANGE_NAME=${AMPQ_EXCHANGE_NAME}

      - LOCAL_AMPQ_HOST=${LOCAL_AMPQ_HOST}
      - LOCAL_AMPQ_PORT=${LOCAL_AMPQ_PORT}
      - LOCAL_AMPQ_QUEUE_NAME=${LOCAL_AMPQ_QUEUE_NAME}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  jasmin_sms_sync_received_msg:
    image: gluontech/jasmin_sms_sync_app
    restart: unless-stopped
    deploy:
      replicas: 1
    environment:
      - AMPQ_HOST=${AMPQ_HOST}
      - AMPQ_VHOST=${AMPQ_VHOST}
      - AMPQ_PORT=${AMPQ_PORT}
      - AMPQ_USERNAME=${AMPQ_USERNAME}
      - AMPQ_PASSWORD=${AMPQ_PASSWORD}
      - AMPQ_QUEUE_NAME=${AMPQ_QUEUE_NAME}.received_messages
      - AMPQ_EXCHANGE_NAME=${AMPQ_EXCHANGE_NAME}.received_messages

      - LOCAL_AMPQ_HOST=${LOCAL_AMPQ_HOST}
      - LOCAL_AMPQ_PORT=${LOCAL_AMPQ_PORT}
      - LOCAL_AMPQ_QUEUE_NAME=${LOCAL_AMPQ_QUEUE_NAME}.received_messages

      - MAX_RE_SYNC_COUNT=${MAX_RE_SYNC_COUNT}

  jasmin_sms_sync_delivery_msg:
    image: gluontech/jasmin_sms_sync_app
    restart: unless-stopped
    deploy:
      replicas: 1
    environment:
      - AMPQ_HOST=${AMPQ_HOST}
      - AMPQ_VHOST=${AMPQ_VHOST}
      - AMPQ_PORT=${AMPQ_PORT}
      - AMPQ_USERNAME=${AMPQ_USERNAME}
      - AMPQ_PASSWORD=${AMPQ_PASSWORD}
      - AMPQ_QUEUE_NAME=${AMPQ_QUEUE_NAME}.delivery_messages
      - AMPQ_EXCHANGE_NAME=${AMPQ_EXCHANGE_NAME}.delivery_messages

      - LOCAL_AMPQ_HOST=${LOCAL_AMPQ_HOST}
      - LOCAL_AMPQ_PORT=${LOCAL_AMPQ_PORT}
      - LOCAL_AMPQ_QUEUE_NAME=${LOCAL_AMPQ_QUEUE_NAME}.delivery_messages

      - MAX_RE_SYNC_COUNT=${MAX_RE_SYNC_COUNT}

  jasmin_sms_sync_redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./cache/redis/data:/data
    restart: unless-stopped
    environment:
      - REDIS_REPLICATION_MODE=master