version: "3"

services:
  jasmin_sms_redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping | grep PONG

  jasmin_sms_amq:
    image: rabbitmq:3-management
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
    ports:
      - 6545:15672

  jasmin_sms_jasmin:
    image: jookies/jasmin:latest
    restart: unless-stopped
    volumes:
      - ./gluon/opt:/opt
      - ./gluon/store:/etc/jasmin/store
      - ./tmp:/tmp
      # - ./gluon/log:/var/log/jasmin
      - ./init.sh:/init.sh
      # - ./jasmin.cfg:/etc/jasmin/jasmin.cfg
    ports:
      - 5634:2775
      - 7687:8990
      - 9345:1401
    entrypoint: sh -c "/init.sh"
    depends_on:
      jasmin_sms_redis:
        condition: service_healthy
      jasmin_sms_amq:
        condition: service_healthy
    environment:
      REDIS_CLIENT_HOST: jasmin_sms_redis
      AMQP_BROKER_HOST: jasmin_sms_amq
